# Project Name
TARGET = uart_receive

# Sources
CPP_SOURCES = uart_receive.cpp pentaPianta.cpp Effect.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy/
DAISYSP_DIR = ../../DaisySP/

LDFLAGS = -u _printf_float


# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
