# Project Name
TARGET = AnalogDelay

# Sources
CPP_SOURCES = src/main.cpp src/AnalogDelay.cpp

# Library Locations
LIBDAISY_DIR = ../libDaisy
DAISYSP_DIR = ../DaisySP

# Include directories
C_INCLUDES += -I.

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile