# Project Name
TARGET = i2cComm

# Sources
CPP_SOURCES = i2cComm.cpp 

# Library Locations
LIBDAISY_DIR = ../../../libs/libDaisy
DAISYSP_DIR = ../../../libs/DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
