# Project Name
TARGET = uart_reciver

# Sources
CPP_SOURCES = uart_reciver.cpp pentaPianta.cpp Effect.cpp

# Library Locations
LIBDAISY_DIR = ../../libs/libDaisy
DAISYSP_DIR = ../../libs/DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
