# Nome del file finale
TARGET = MidiFMajor

# File sorgente
CPP_SOURCES = main.cpp

# Percorso relativo per arrivare alla cartella libDaisy
# Se le cartelle sono affiancate come nello schema sopra, si usa ../libDaisy
LIBDAISY_DIR = ../libDaisy

# Inclusione del sistema di build core
include $(LIBDAISY_DIR)/core/Makefile